
#startportainer
  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: unless-stopped
    hostname: portainer
    command: --no-auth
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:@PORTAINER_FQDN@
      - traefik.port=9000
      - traefik.docker.network=@PROXY_NETWORK@
      - traefik.frontend.auth.basic=@MDP@
    volumes:
      - /opt/seedbox/conf/admin/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
#endportainer
