
#startmedusa
  medusa-@USERNAME@:
    image: linuxserver/medusa
    container_name: medusa-@USERNAME@
    restart: unless-stopped
    hostname: medusa
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:@MEDUSA_FQDN@
      - traefik.port=8081
      - traefik.docker.network=@PROXY_NETWORK@
      - traefik.frontend.auth.basic=@MDP@
    volumes:
      - @SHOME@/Medias/TV:/tv
      - @SHOME@/rutorrent/downloads:/downloads
      - @SHOME@/docker/medusa/config:/config
    environment:
      - /etc/localtime:/etc/localtime:ro
      - TZ=Paris/Europe
      - PUID=@PUID@
      - PGID=@PGID@
    networks:
      - proxy
#endmedusa
