
#startwatchtower
  watchtower:
    container_name: watchtower
    hostname: watchtower
    restart: unless-stopped
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup
    networks:
      - proxy
#endwatchtower
