version: '3'
services:

  traefik:
    image: traefik
    container_name: traefik
    restart: unless-stopped
    hostname: traefik
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:@TRAEFIK_DASHBOARD_URL@
      - traefik.port=8080
      - traefik.docker.network=@PROXY_NETWORK@
      - traefik.frontend.auth.basic=@VAR@
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - @VOLUMES_TRAEFIK_PATH@/traefik.toml:/traefik.toml:ro
      - @VOLUMES_TRAEFIK_PATH@/certs:/etc/traefik/acme:rw
      - /var/log/traefik:/var/log
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy
    command:
      - --web
      - --accessLog.filePath=/var/log/access.log
      - --accessLog.filters.statusCodes=400-499

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:@DOMAIN@
      - traefik.port=80
      - traefik.docker.network=@PROXY_NETWORK@
    volumes:
      - /var/www/html:/usr/share/nginx/html
    networks:
      - proxy

networks:
  proxy:
    external:
      name: @PROXY_NETWORK@

